version: '1.0'
name: pipeline-20230924
displayName: 发布到pypi
triggers:
  trigger: auto
  push:
    tags:
      include:
        - v\d\.\d\.\d
variables:
  global:
    - pypi_account_token
stages:
  - name: stage-3cc1e226
    displayName: pytest
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: ut@python
        name: unit_test_python
        displayName: Python 单元测试
        pythonVersion: '3.9'
        commands:
          - ''
          - '# 查看文件列表'
          - ls
          - ''
          - '# 构建依赖'
          - pip install -U -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple --force-reinstall
          - ''
          - '# Python单元测试默认命令'
          - pytest --html=report/index.html
        report:
          path: report
          index: index.html
        checkpoints:
          - key: TestPassRate
            value: 100
            logicalOperator: '&&'
            relationalOperator: '>='
        caches: []
        notify:
          - certificate: 19b73520-9089-013d-19d6-3ee4d8100835
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
  - name: stage-5d5de195
    displayName: 编译-发布到pypi
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - '# 可以使用pip下载依赖'
          - python --version
          - ''
          - '# 安装项目依赖'
          - '# pip install --user -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple'
          - ''
          - '# 安装指定打包模块'
          - pip install setuptools wheel twine==4
          - ''
          - '# 编译为wheel包'
          - python setup.py bdist_wheel
          - ''
          - '# 上传到pipy环境'
          - python -m twine upload dist/* -u __token__ -p ${pypi_account_token}
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify:
          - certificate: 19b73520-9089-013d-19d6-3ee4d8100835
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '1'
