version: '1.0'
name: pipeline-20230922
displayName: 发布到pypi_test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
    paths:
      precise:
        - setup.py
      include:
        - webdrivermanager_cn/*
variables:
  global:
    - pypi_test_account_token
stages:
  - name: stage-3cda854d
    displayName: wheel 文件构建并发布
    strategy: naturally
    trigger: auto
    executor:
      - Joker_JH
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.8'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - '# 可以使用pip下载依赖'
          - python --version
          - ''
          - '# 安装项目依赖'
          - pip install --user -r requirements.txt
          - ''
          - '# 安装指定打包模块'
          - pip install setuptools wheel twine
          - ''
          - '# 编译为wheel包'
          - python setup.py bdist_wheel
          - ''
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '2'
  - name: stage-a87afbd4
    displayName: 成果物产出
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: SourceCode
        notify: []
        strategy:
          retry: '0'
  - name: stage-e9ff7938
    displayName: 发布到pypi_test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - '# 可以使用pip下载依赖'
          - python --version
          - ''
          - '# 安装项目依赖'
          - pip install --user -r requirements.txt
          - ''
          - '# 安装指定打包模块'
          - pip install setuptools wheel twine
          - ''
          - '# 编译为wheel包'
          - python setup.py bdist_wheel
          - ''
          - '# 上传到pipy测试环境'
          - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${pypi_test_account_token}
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify:
          - certificate: 334a41c0-3d9b-013c-b51a-0efef618f381
            events:
              - success
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: weixin
        strategy:
          retry: '3'
