version: '1.0'
name: pipeline-20230922
displayName: 发布到测试pipy
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-3cda854d
    displayName: step1
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.8'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - '# 可以使用pip下载依赖'
          - python --version
          - ''
          - '# 安装项目依赖'
          - pip install --user -r requirements.txt
          - ''
          - '# 安装指定打包模块'
          - pip install setuptools wheel twine
          - ''
          - '# 编译为wheel包'
          - 'python setup.py bdist_wheel '
          - ''
          - '# 上传到pipy测试环境'
          - twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${pipy_user} -p ${pipy_pwd}
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
