version: '1.0'
name: pipeline-20230924
displayName: 发布到pypi
triggers:
  trigger: auto
  push:
    tags:
      include:
        - v\d\.\d\.\d
variables:
  global:
    - pypi_account_token
stages:
  - name: stage-5d5de195
    displayName: 编译-发布到pypi
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - ''
          - '# 可以使用pip下载依赖'
          - python --version
          - ''
          - '# 安装项目依赖'
          - pip install --user -r requirements.txt
          - ''
          - '# 安装指定打包模块'
          - pip install setuptools wheel twine
          - ''
          - '# 编译为wheel包'
          - python setup.py bdist_wheel
          - ''
          - '# 上传到pipy环境'
          - python -m twine upload dist/* -u __token__ -p ${pypi_account_token}
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '1'
